#!/bin/bash

# script sympa pour ne pas avoir a rentrer ses creds 500 fois pour sentinel ASR :))))))))

if [ $# -eq 0 ]; then
    echo "USAGE : ./wadbot [push | sentinel]"
    exit 0
fi
argument="$1"
if [ "$argument" = "push" ]; then
    echo "wadbot na blyat ski pushi zjinya"
elif [ "$argument" = "sentinel" ]; then
    echo "wadbot na blyat ya ore no [S A N T I N E R U]-sama"
else
    echo "USAGE : ./wadbot [push | sentinel]"
    exit 0
fi
echo "Prenom :"
read prenom
echo "Nom :"
read nom

echo "Exo"
echo "--> "
read repo

echo "Quel exo ${repo} ? :"
read asr_nbr
echo "nom du commit :"
read cummit
git config --global user.name "${prenom} ${nom}"
git config --global user.email "${prenom}.${nom}@ecole2600.com"
git config --global credential.helper store

fullpath="https://git.ecole2600.com/promo2026_RNCP35612/${prenom}.${nom}_${repo}-exos-${asr_nbr}-2025.git"
git clone $fullpath

cd "${prenom}.${nom}_${repo}-exos-${asr_nbr}-2025/"
curl https://sentinel.ecole2600.com/download/latest -o sentinel
chmod +x sentinel
git add .
git commit -m "${cummit}"
if [ "$argument" = "push" ]; then
    git push
elif [ "$argument" = "sentinel" ]; then
    ./sentinel
fi
cd ../
rm -rf "${prenom}.${nom}_${repo}-exos-${asr_nbr}-2025/"
rm -rf .gitconfig
git config --global --unset credential.helper
rm -rf .git-credentials

echo "WADBOT COMPLETE."
