#!/bin/bash

if [ $# -eq 0 ]; then
    echo "USAGE : ./wadbot [push | sentinel]"
    exit 0
fi
argument="$1"
if [ "$argument" = "push" ]; then
    echo "wadbot na blyat ski pushi zjinya"
elif [ "$argument" = "sentinel" ]; then
    echo "wadbot na blyat ya ore no [S A N T I N E R U]-sama"
else
    echo "USAGE : ./wadbot [push | sentinel]"
    exit 0
fi
echo "Prenom (don't forget les majuscules) :"
read prenom
echo "Nom (don't forget les majuscules) :"
read nom

echo "Exos ?"
echo "1 - C"
echo "2 - ASM"
echo "3 - Python"
echo "4 - ASR"
echo "5 - DB"
echo "--> "
read repo
if [ "$repo" = "1" ]; then
    echo "C selected."
    $repo="c"
elif [ "$repo" = "2" ]; then
    echo "ASM selected."
    $repo="asm"
elif [ "$repo" = "3" ]; then
    echo "Python selected."
    $repo="pythonsec"
elif [ "$repo" = "4" ]; then
    echo "ASR selected."
    $repo="asr"
elif [ "$repo" = "5" ]; then
    echo "DB selected."
    $repo="db"
else
    echo "custom repo name set."
fi

echo "Quel exo ${repo} ? :"
read asr_nbr
echo "nom du commit :"
read cummit
git config --global user.name "${prenom} ${nom}"
git config --global user.email "${prenom}.${nom}@ecole2600.com"
git config --global credential.helper store

fullpath="https://git.ecole2600.com/promo2026_RNCP35612/${prenom}.${nom}_${repo}-exos-${asr_nbr}-2025.git"
git clone $fullpath

cd "${prenom}.${nom}_${repo}-exos-${asr_nbr}-2025/"
curl https://sentinel.ecole2600.com/download/latest -o sentinel
chmod +x sentinel
git add .
git commit -m "${cummit}"
if [ "$argument" = "push" ]; then
    git push
elif [ "$argument" = "sentinel" ]; then
    ./sentinel
fi
cd ../
rm -rf "${prenom}.${nom}_${repo}-exos-${asr_nbr}-2025/"
rm -rf .gitconfig
git config --global --unset credential.helper
rm -rf .git-credentials

echo "WADBOT COMPLETE."
